name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest

          - name: Android32
            os: ubuntu-latest
            target: Android32

          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode CLI and SDK
        run: |
          if [ "${{ matrix.config.os }}" = "windows-latest" ]; then
            curl -LO https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-v3.7.4-win.zip
            7z x geode-cli-v3.7.4-win.zip -y -o"$HOME/custom-geode-cli"
            echo "$HOME/custom-geode-cli" >> $GITHUB_PATH
            export PATH="$HOME/custom-geode-cli:$PATH"
            
            # 🚀 THE FIX: Create dummy profile directory and file for Windows
            mkdir -p "$vivid_profile_path" # safety
            mkdir -p "$LOCALAPPDATA/Geode"
            echo '{"current-profile": "default", "profiles": {"default": {"name": "default", "gd-path": "C:\\"}}}' > "$LOCALAPPDATA/Geode/config.json"
            
            geode sdk install
          else
            curl -LO https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-v3.7.4-linux.zip
            mkdir -p $HOME/custom-geode-cli
            unzip -o geode-cli-v3.7.4-linux.zip -d $HOME/custom-geode-cli
            chmod +x $HOME/custom-geode-cli/geode
            echo "$HOME/custom-geode-cli" >> $GITHUB_PATH
            export PATH="$HOME/custom-geode-cli:$PATH"
            
            # 🚀 THE FIX: Create dummy profile directory and file for Linux/Android
            mkdir -p "$HOME/.config/Geode"
            echo '{"current-profile": "default", "profiles": {"default": {"name": "default", "gd-path": "/"}}}' > "$HOME/.config/Geode/config.json"
            
            geode sdk install
          fi
        shell: bash

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
